title: Belico Website
description: 벨리코 맞춤형 깔창 웹사이트
baseurl: "/Belico-Website"
url: "https://jyongchul.github.io"

plugins:
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

exclude:
  - node_modules/
  - server.js
  - package.json
  - package-lock.json
  - CLAUDE.md